# Configuration for FreePose
freepose:
  method: "FreePoseMethod"  # e.g., "method_name"
  dataset_path: "/home/huangyue/Mycodes/MetaScenes/examples/scannet_example"
  asset_path: "/home/huangyue/Mycodes/MetaScenes/examples/free_pose_mesh"
  output_path: "/home/huangyue/Mycodes/MetaScenes/pose_alignment_output"
  inst_name_dir: "/home/huangyue/Mycodes/MetaScenes/examples/scannet_example"
  init_pose: # !!python/ndarray
    - [ 1, 0, 0, 0 ]
    - [ 0, 0, -1, -2 ]
    - [ 0, 1, 0, 0 ]
    - [ 0, 0, 0, 1 ]


# Configuration for AlignedPose
alignedpose:
  method: "AlignedPoseMethod"  # e.g., "method_name"
  dataset_path: "/home/huangyue/Mycodes/MetaScenes/examples/scannet_example"
  asset_path: "/home/huangyue/Mycodes/MetaScenes/examples/aligned_pose_mesh"
  output_path: "/home/huangyue/Mycodes/MetaScenes/pose_alignment_output"
  inst_name_dir: "/home/huangyue/Mycodes/MetaScenes/examples/scannet_example"

